CREATE TABLE IF NOT EXISTS BOARD (
    ID bigint NOT NULL AUTO_INCREMENT,
    TITLE CHAR(30) NOT NULL,
    AUTHOR CHAR(30) NOT NULL,
    PASSWORD CHAR(30) NOT NULL,
    CONTENT CHAR(30) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);