spring:
  docker:
    compose:
      enabled: true
      file: compose.yml

  sql:
    init:
      schema-locations: classpath*:db/schema.sql
      mode: always # default? embedded?? always ??? ??

  r2dbc:
    url: r2dbc:mysql://localhost:3306/mydb
    username: root
    password: example0000

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

springdoc:
  version: "0.1.0"
  default-consumes-media-type: application/json
  default-produces-media-type: application/json